<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
    <PackageReference Include="xunit.v3"/>
    <PackageReference Include="FakeItEasy"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="SharpHook.Testing"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pisum.Whisper.Core\Pisum.Whisper.Core.csproj"/>
  </ItemGroup>

</Project>
